export const EXPENSE_CREATE_REQUEST = "EXPENSE_CREATE_REQUEST";
export const EXPENSE_CREATE_SUCCESS = "EXPENSE_CREATE_SUCCESS";
export const EXPENSE_CREATE_FAILURE = "EXPENSE_CREATE_FAILURE";

export const EXPENSE_LIST_ALL_REQUEST = "EXPENSE_LIST_ALL_REQUEST";
export const EXPENSE_LIST_ALL_SUCCESS = "EXPENSE_LIST_ALL_SUCCESS";
export const EXPENSE_LIST_ALL_FAILURE = "EXPENSE_LIST_ALL_FAILURE";

export const EXPENSE_LIST_BY_USER_REQUEST = "EXPENSE_LIST_BY_USER_REQUEST";
export const EXPENSE_LIST_BY_USER_SUCCESS = "EXPENSE_LIST_BY_USER_SUCCESS";
export const EXPENSE_LIST_BY_USER_FAILURE = "EXPENSE_LIST_BY_USER_FAILURE";

export const EXPENSE_DETAILS_REQUEST = "EXPENSE_DETAILS_REQUEST";
export const EXPENSE_DETAILS_SUCCESS = "EXPENSE_DETAILS_SUCCESS";
export const EXPENSE_DETAILS_FAILURE = "EXPENSE_DETAILS_FAILURE";

export const EXPENSE_UPDATE_REQUEST = "EXPENSE_UPDATE_REQUEST";
export const EXPENSE_UPDATE_SUCCESS = "EXPENSE_UPDATE_SUCCESS";
export const EXPENSE_UPDATE_FAILURE = "EXPENSE_UPDATE_FAILURE";

export const EXPENSE_DELETE_REQUEST = "EXPENSE_DELETE_REQUEST";
export const EXPENSE_DELETE_SUCCESS = "EXPENSE_DELETE_SUCCESS";
export const EXPENSE_DELETE_FAILURE = "EXPENSE_DELETE_FAILURE";
