export const EXPENSE_CREATE_REQUEST = "EXPENSE_CREATE_REQUEST";
export const EXPENSE_CREATE_SUCCESS = "EXPENSE_CREATE_SUCCESS";
export const EXPENSE_CREATE_FAILURE = "EXPENSE_CREATE_FAILURE";

export const EXPENSE_LIST_ALL_REQUEST = "EXPENSE_LIST_ALL_REQUEST";
export const EXPENSE_LIST_ALL_SUCCESS = "EXPENSE_LIST_ALL_SUCCESS";
export const EXPENSE_LIST_ALL_FAILURE = "EXPENSE_LIST_ALL_FAILURE";

export const EXPENSE_LIST_BY_USER_REQUEST = "EXPENSE_LIST_BY_USER_REQUEST";
export const EXPENSE_LIST_BY_USER_SUCCESS = "EXPENSE_LIST_BY_USER_SUCCESS";
export const EXPENSE_LIST_BY_USER_FAILURE = "EXPENSE_LIST_BY_USER_FAILURE";
